---
- hosts: 172.31.27.164
  become: yes
  tasks:
  - name: i want to install git
    apt:
     name: git
     state: present
    tags: mygit 

  - name: i want to install tree
    apt:
     name: tree
     stte: present
    tags: mytree 

  - name: i want to install wget
    apt: 
     name: wget
     state: present
    tags: mywget     
