---
- hosts: 172.31.27.164
  become: yes
  tasks:
  - include_tasks: myfile.yml  

  - name: i want to install webserver
    apt:
     name: apache2
     state: present

  - name: i want to copy index into node side  
    copy:
     src: myindex.html
     dest: /var/www/html/index.html