---
- hosts: 172.31.27.164
  become: yes
  tasks:
  - include_tasks: myfile.yml  

  - name: i want to install webserver
    apt:
     name: apache2
     state: present

  - name: i want to copy index into node side  
    copy:
     src: myindex.html
     dest: /var/www/html/index.html

  - name: i want to copy myindex.j2 into nodes side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html  
  
  - name: download onto nodes side
    get_url:
     url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes
