--- 
- hosts: all
  become: yes
  tasks:
   - name: i want to install apache2 on my node server
     apt:
      - name: apache2
        state: present

   - name: i want to run apache2 installed on my node server
     service: 
      - apt: apache2
        state: started  