--- 
- hosts: all
  become: yes
  tasks:
   - name: i want to install on my node server
     apt:
       name: apache2
       state: present

   - name: i want to run installed on my node server
     service: 
       - name: apache2
         state: started  